import "./body.css"

export const Body = () => {

    return(

        <div className={"body-div"}>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores at dolore doloremque est facere fuga incidunt labore maiores minima minus natus nulla numquam obcaecati quia rerum sunt suscipit, voluptas voluptatum!
        </div>
    )
}
