export const SET_LIBRARIES = "SET_LIBRARIES";
export const SET_WORDS = "SET_WORDS";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_PARTSOFSPEECH = "SET_PARTSOFSPEECH";
export const SET_LETTER = "SET_LETTER";
export const SET_USER = "SET_USER";
export const SET_RANDOM = "SET_RANDOM";
export const SET_PAGINATION = "SET_PAGINATION";
export const SET_LIBS_PAGINATION = "SET_LIBS_PAGINATION";
export const SET_SEARCH_PAGINATION = "SET_SEARCH_PAGINATION";

